{% set name = "causalnex" %}
{% set version = "0.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/causalnex-{{ version }}.tar.gz
  sha256: 99f96ab5595404622a62e916faae0a2a2b1ac9142213b9e9d8892f8d7b993b11

build:
  skip: true  # [py>=39 or py2k or win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python
    - pip
  run:
    - python
    - networkx >=2.5,<3.dev0
    - numpy >=1.14.2,<1.24.0
    - pandas >=1.0,<2.0
    - pathos >=0.2.7,<0.3.0
    - pgmpy >=0.1.14,<0.1.21
    - scikit-learn >=0.22.0,<0.25.0,!=0.22.2.post1,!=0.24.1  # [py<39]
    - scikit-learn >=0.24.0,<0.25.0,!=0.24.1  # [py==39 ]
    - scikit-learn >=0.25.0  # [py==310 ]
    - scipy >=1.7
    - pytorch >=1.7,<2.0
    - wrapt >=1.11.0,<1.13
    - ipython >=8.10,<9.0

test:
  imports:
    - causalnex
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/quantumblacklabs/causalnex
  summary: Toolkit for causal reasoning (Bayesian Networks / Inference)
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - JohanMabille
